travis:
  secure:
    BINSTAR_TOKEN: SQppgG89t3UsuaPz2Qwk499ZRriynngvwyQJuq1I3HaIIYgGEQ2/p/8cS3sFOVzhT/bHgsDsGwg/trcSzLrqixsLARgpj07b9VWcmy9ftImlQ1AMdelCr4nwshqaiW+xXk+HxLSs3so59xtokdfnm8h3U4cOQGUkSJTc5pkVEf3y5REuMUQa8m4m081TVV19qzjhCZOh/f+C8OtHCfhXpbFEY4wAOGTkoE67L+DXBKaxqgPRyf54XplP0mRuPpOPYZdH3JQ9DGQI/xz0rofXVZDmGdaru6dzlVl+8gKRg3ZHsKeGN4F+SHMMrWEiqGY8EqSa8qDDGmmX/fIxmq6uxQ2zkavkgZ9f2FGmJe7+4IxPpautdrXnCDflJjc4xIPJoL63mfi7AOD6wJlKp0FVYNHFEAlQ2Kb3pBjv8CpISaGSm8SJlMNjhgpRt/hmLDpxgIRM4LHXD7PluusveF/aXunM9Mqh6u2Mo1XRW/BYzIlXZfRdjPPLuoi2XG3e9hFEIuLCVKGj5CGHrmpsMyvjgLzTQIy1OP0BCTPdGRQ1T3Z0Ly600+prsRT47vKjzN6xm7ZOy8qkl/Wd39gqusytaHFAR75TAB3qugyoE5gGT5RJLeA6yDMBYTqy5WmUcyoC6tt4a/E2y+s0EKtPGOiGtvomnb7xcOntotd9oz+eL3A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
