travis:
  secure:
    BINSTAR_TOKEN: CpjjjC9A/LyRQDjcMWD5FT8kf3SH3+S4CTgail9KCIGAxiZGVSEB4GUqhhrROYsLB/ATuQ25J867JXqAwgcd99eztjlNY/3zZKaAVi/2RL9Y6AJeqt2Zxhk4rpYJ3NFhZVdwoRiFC9CNC59Mp41DIOjBg79z7kj+C8ndFpSPbYUmlB9Tq9IJoVIlrbfIFetmIr+NBbuVBiiJjCoImn6yroS2Jq0FwM7qEWi2nI77HMP7qMcICZMVvosGecvCH07+INK5y20Q/1pUEIdmsXavjFJ+PRsM+O0aO1uxIlT81RRMgOvF2Vq3wewEuL32vTeT/cMYNKNsyvMPpw2DiXQZTOCaIcJ/iXR7ABHWuhn25olAq8arYElImi1C+uflvaFHCT77BDeo+muqnrtNrbuyFZQSiMhxS6QN+4b5xIuU2cSypNYmsAON1V3FSGsXBxf2KD2LF4HU1qieJMLf2r8pvZ2NAjzmPh1pEw3sgSRBYt/NSyd8quvEZJMzcMBAXSU0+s7toJvbdRVL8cWSe7enK912yBwi/FbJem5xaPtbXFZTOfNdFwuox9d8f5bCU1TMXkHXUUdAX8HSewG7lpV6tbhCCOPGoCFe9fZCwCFPvYb/+J3r62gQXngYWMUsOeAW9N9A9u/M7fbzVljL5vvErwqcnOqPh8G4+oaA337U5UQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
